In [2]:
import numpy as np
import pandas as pd

test = pd.read_csv('test_result/full_leaderboard.csv')

In [3]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Experiment_Name              84 non-null     object
 1   Run_Time                     84 non-null     object
 2   model                        84 non-null     object
 3   score_val                    84 non-null     float64
 4   eval_metric                  84 non-null     object
 5   pred_time_val                84 non-null     float64
 6   fit_time                     84 non-null     float64
 7   pred_time_val_marginal       84 non-null     float64
 8   fit_time_marginal            84 non-null     float64
 9   stack_level                  84 non-null     int64
 10  can_infer                    84 non-null     bool
 11  fit_order                    84 non-null     int64
 12  num_features                 84 non-null     int64
 13  num_models                   84 non-null     int64
 14  num_models_w_ancestors       84 non-null     int64
 15  memory_size                  84 non-null     int64
 16  memory_size_w_ancestors      84 non-null     int64
 17  memory_size_min              84 non-null     int64
 18  memory_size_min_w_ancestors  84 non-null     int64
 19  num_ancestors                84 non-null     int64
 20  num_descendants              84 non-null     int64
 21  model_type                   84 non-null     object
 22  child_model_type             84 non-null     object
 23  stopping_metric              84 non-null     object
 24  hyperparameters              84 non-null     object
 25  hyperparameters_fit          84 non-null     object
 26  ag_args_fit                  84 non-null     object
 27  features                     84 non-null     object
 28  compile_time                 0 non-null      float64
 29  child_hyperparameters        84 non-null     object
 30  child_hyperparameters_fit    84 non-null     object
 31  child_ag_args_fit            84 non-null     object
 32  ancestors                    84 non-null     object
 33  descendants                  84 non-null     object
dtypes: bool(1), float64(6), int64(11), object(16)
memory usage: 21.9+ KB

In [5]:
test.sort_values(by='score_val', ascending=False).drop_duplicates(subset=['model'])[['Experiment_Name','model', 'score_val', 'features']].head()

,Experiment_Name,model,score_val,features
30,no weight,WeightedEnsemble_L3,0.793804,"['LightGBM_BAG_L2', 'ExtraTrees_BAG_L2', 'Rand..."
55,no call,ExtraTrees_BAG_L2,0.790443,"['Discount_Group', 'Prior_purchases', 'LinearM..."
32,no weight,RandomForest_BAG_L2,0.786706,"['Discount_Group', 'Discount_rate', 'log_price..."
57,no call,CatBoost_BAG_L2,0.770871,"['Discount_Group', 'Prior_purchases', 'LinearM..."
58,no call,LightGBM_BAG_L2,0.768045,"['Discount_Group', 'Prior_purchases', 'LinearM..."

In [6]:
col = ['child_hyperparameters', 'child_hyperparameters_fit', 'child_ag_args_fit', 'ancestors', 'descendants']

In [7]:
test.sort_values(by='score_val', ascending=False).drop_duplicates(subset=['model'])[col].head()

,child_hyperparameters,child_hyperparameters_fit,child_ag_args_fit,ancestors,descendants
30,"{'ensemble_size': 25, 'subsample_size': 1000000}",{'ensemble_size': 24},"{'max_memory_usage_ratio': 1.0, 'max_time_limi...","['RandomForest_BAG_L2', 'ExtraTrees_BAG_L2', '...",[]
55,"{'n_estimators': 300, 'max_leaf_nodes': 15000,...",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limi...","['LinearModel_BAG_L1', 'CatBoost_BAG_L1', 'Ran...",['WeightedEnsemble_L3']
32,"{'n_estimators': 300, 'max_leaf_nodes': 15000,...",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limi...","['LinearModel_BAG_L1', 'CatBoost_BAG_L1', 'Ran...",['WeightedEnsemble_L3']
57,"{'iterations': 10000, 'learning_rate': 0.05, '...",{'iterations': 206},"{'max_memory_usage_ratio': 1.0, 'max_time_limi...","['LinearModel_BAG_L1', 'CatBoost_BAG_L1', 'Ran...",['WeightedEnsemble_L3']
58,"{'learning_rate': 0.05, 'seed': 0}",{'num_boost_round': 163},"{'max_memory_usage_ratio': 1.0, 'max_time_limi...","['LinearModel_BAG_L1', 'CatBoost_BAG_L1', 'Ran...",['WeightedEnsemble_L3']